# Generated by Django 5.1.7 on 2025-05-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_product_favourite_favourite'),
        ('media', '0002_productclassimage_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.category'),
        ),
        migrations.AlterField(
            model_name='productclassimage',
            name='image_product_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.productclass'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.product'),
        ),
    ]
