# Generated by Django 5.1.7 on 2025-05-15 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_product_view_count'),
        ('media', '0003_alter_categoryimage_image_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.product'),
            preserve_default=False,
        ),
    ]
