# Generated by Django 5.1.7 on 2025-05-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_discount_price_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
