# Generated by Django 5.1.7 on 2025-05-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
